// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallParticipant } from "./CallParticipant";

/**
 * Signaling-level state of a room's MatrixRTC call (MSC3401 room-scope
 * `m.call` memberships).
 */
export type CallState = { room_id: string, 
/**
 * Everyone with an unexpired call membership, oldest first. A user
 * joined from two devices appears twice.
 */
participants: Array<CallParticipant>, 
/**
 * Whether *this* device has an active membership (not just this user
 * — the same account joined from a phone doesn't count).
 */
joined: boolean, };
