// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CustomEmoji = { shortcode: string, mxc_url: string, 
/**
 * MSC2545 usage flags. An image that declares no usage is usable as
 * *both*, so both default to true — the emoji picker shows the
 * `is_emoticon` images, the sticker picker shows the `is_sticker` ones.
 */
is_emoticon: boolean, is_sticker: boolean, 
/**
 * Intrinsic dimensions from the pack's per-image `info` block, when the
 * pack declares them — used to render stickers at true aspect and to
 * fill the `m.sticker` event's `ImageInfo` on send.
 */
width: number | null, height: number | null, };
