// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomEmoji } from "./CustomEmoji";

export type EmojiPack = { name: string, emojis: Array<CustomEmoji>, };
