// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which account-wide default a `ClientCommand::SetDefaultNotificationMode`
 * targets. The SDK models this as a 4-way matrix (encrypted x one-to-one),
 * but the UI only exposes these two buckets — setting either one writes
 * both the encrypted and unencrypted variant together.
 */
export type NotificationScope = "DirectMessages" | "GroupChats";
