// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One MSC3949 power-level tag: a named (optionally colored) member group
 * anchored at a power level. Members belong to the tag at their level,
 * falling back to the nearest lower defined tag.
 */
export type PowerLevelTag = { level: number, name: string, 
/**
 * Hex color like `#ff0000`, when the room defined one.
 */
color: string | null, };
