// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReactionGroup = { 
/**
 * The raw annotation key: a unicode emoji, or a custom-emoji shortcode
 * like `:hq_wave:` if that's what the sender's client sent.
 */
key: string, count: number, reacted_by_me: boolean, 
/**
 * User IDs of everyone who sent this reaction (hover attribution).
 */
senders: Array<string>, };
