// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReplyPreview = { event_id: string, 
/**
 * Display name (or user id) of the quoted message's sender; empty when
 * the SDK hasn't loaded the replied-to event's details.
 */
sender: string, snippet: string, 
/**
 * Set when the quoted message is an image — quotes render it as a
 * small thumbnail.
 */
image_url: string | null, };
