// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoomMember = { user_id: string, display_name: string, avatar_url: string | null, 
/**
 * Matrix power level (0 = default member, 50 = moderator by
 * convention, 100 = admin) — drives the member list's grouping.
 */
power_level: number, };
