// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoomSummary = { room_id: string, name: string, topic: string | null, avatar_url: string | null, unread_count: number, is_encrypted: boolean, is_space: boolean, 
/**
 * Marked as a direct message via `m.direct` account data.
 */
is_dm: boolean, last_message_preview: string | null, };
