// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SasState = { "type": "RequestReceived", "data": { from_user_id: string, } } | { "type": "RequestSent" } | { "type": "Ready" } | { "type": "EmojisReady", "data": Array<[string, string]> } | { "type": "WaitingForOtherPartyConfirmation" } | { "type": "Done" } | { "type": "Cancelled", "data": { reason: string, } };
