// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * See [`TimelineItem::send_failed`].
 */
export type SendFailure = { 
/**
 * Recoverable errors (e.g. a timeout) can be retried by simply
 * re-enabling the room's send queue; unrecoverable ones ("wedged")
 * can't be fixed that way, so the UI shouldn't offer a Retry action for
 * them (see `ClientCommand::RetrySend`'s doc comment).
 */
is_recoverable: boolean, error: string, };
