// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a space child can be entered, reduced to the cases the explorer UI
 * distinguishes (the spec's `SpaceRoomJoinRule` is wider).
 */
export type SpaceJoinRule = "Public" | "Restricted" | "Knock" | "InviteOnly";
