// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpaceJoinRule } from "./SpaceJoinRule";

/**
 * One room (or subspace) listed under a space by the space-hierarchy API.
 * Unlike `RoomSummary` this can describe rooms the account hasn't joined —
 * that's the point of the space explorer.
 */
export type SpaceChildSummary = { room_id: string, 
/**
 * `None` when the room publishes no name — display falls back to the
 * alias, then the room id.
 */
name: string | null, topic: string | null, canonical_alias: string | null, avatar_url: string | null, num_joined_members: number, 
/**
 * This child is itself a space (the explorer drills in rather than
 * opening a timeline).
 */
is_space: boolean, 
/**
 * Whether this account already belongs to the room.
 */
joined: boolean, join_rule: SpaceJoinRule, 
/**
 * Candidate servers for joining, from the parent space's
 * `m.space.child` event — needed when our homeserver isn't already in
 * the room. Empty is fine for rooms it knows.
 */
via: Array<string>, };
