// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncState = { "type": "Connecting" } | { "type": "Syncing" } | { "type": "Offline" } | { "type": "Error", "data": string };
