// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineItem } from "./TimelineItem";

/**
 * One structural change to a room's timeline window, mirroring the SDK's
 * `eyeball_im::VectorDiff` over already-converted [`TimelineItem`]s (indices
 * are in the UI list's space — the worker has already dropped the SDK's
 * content-less `TimelineStart` marker and renumbered accordingly). Applied in
 * order by the UI; see [`ClientEvent::TimelineDiffs`].
 */
export type TimelineDiff = { "type": "Append", "data": Array<TimelineItem> } | { "type": "Clear" } | { "type": "PushFront", "data": TimelineItem } | { "type": "PushBack", "data": TimelineItem } | { "type": "PopFront" } | { "type": "PopBack" } | { "type": "Insert", "data": { index: number, item: TimelineItem, } } | { "type": "Set", "data": { index: number, item: TimelineItem, } } | { "type": "Remove", "data": { index: number, } } | { "type": "Truncate", "data": { length: number, } } | { "type": "Reset", "data": Array<TimelineItem> };
