// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReactionGroup } from "./ReactionGroup";
import type { ReplyPreview } from "./ReplyPreview";
import type { SendFailure } from "./SendFailure";
import type { TimelineItemContent } from "./TimelineItemContent";
import type { TrustShield } from "./TrustShield";

export type TimelineItem = { event_id: string | null, sender: string, sender_display_name: string | null, sender_avatar_url: string | null, timestamp_ms: number, content: TimelineItemContent, 
/**
 * The message's `formatted_body` (HTML) after sanitizing per the Matrix
 * spec's allowed element/attribute list, for text, emote and notice
 * messages that carry one. `None` means render `content`'s plain body.
 * The frontend sanitizes again before inserting it into the DOM.
 */
formatted_body: string | null, 
/**
 * Trust indicator for encrypted messages, mirroring `matrix-sdk-ui`'s
 * `ShieldState` (lax mode — matches what Element shows by default).
 * `None` means no shield should be shown (unencrypted, local echo, or
 * verified-and-trusted).
 */
shield: TrustShield | null, reactions: Array<ReactionGroup>, 
/**
 * Set if this message is a reply within a thread; `None` for the main
 * timeline. Only the thread root carries `thread_reply_count`.
 */
thread_root: string | null, thread_reply_count: number | null, 
/**
 * User IDs with a read receipt exactly on this event (not "read up to
 * and including" — matrix-sdk-ui attaches receipts per-event already).
 */
read_by: Array<string>, 
/**
 * Set when this message is a rich reply — who/what it quotes.
 */
in_reply_to: ReplyPreview | null, 
/**
 * This message has been edited (an `m.replace` aggregation was applied
 * by matrix-sdk-ui) — the UI appends a subdued "(edited)" tag. Always
 * `false` for non-message items.
 */
edited: boolean, 
/**
 * Set when this is a local echo whose send attempt failed (mirrors
 * matrix-sdk-ui's `EventSendState::SendingFailed`). `None` covers both
 * a normally-sent message and a local echo still in flight — only a
 * send that has actually failed needs a UI affordance.
 */
send_failed: SendFailure | null, };
