// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * OpenGraph-style link preview, as returned by the homeserver's
 * `/media/preview_url` endpoint. `image_mxc` is an `mxc://` URI (the
 * homeserver re-hosts the remote image), fetchable through the normal
 * media path.
 */
export type UrlPreview = { url: string, title: string | null, description: string | null, site_name: string | null, image_mxc: string | null, 
/**
 * `og:image:width`/`height` when the homeserver reports them — used to
 * tell square avatars from attached media in tweet cards.
 */
image_width: number | null, image_height: number | null, };
