// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One hit from a user-directory search — enough to render a pick-a-person
 * row and start a DM with them (even someone you share no room with yet).
 */
export type UserSearchResult = { user_id: string, display_name: string | null, avatar_url: string | null, };
